### ISSUE TITLE
error

### ISSUE THREAD

**Issue by imnew827** [depthso/Roblox-Botter#1]
starting ROBLOX...
Traceback (most recent call last):
  File "D:\Roblox-Botter\accjoin.py", line 87, in <module>
    Cookie = config["Cookies"][i]
IndexError: list index out of range

**Comment by depthso** [comment]
How many cookies did you provide because if you have 2 but you have set the bot count as 6, it will result in this error given.

**Comment by imnew827** [comment]
one cookkie

**Comment by depthso** [comment]
Sorry for the late response but, did you change the variable **Bots** on line 83 to one?

**Comment by imnew827** [comment]
yep worked thank u
