### ISSUE TITLE
error

### ISSUE THREAD

**Issue by op-lum1x** [depthso/Roblox-Botter#2]
hello bro, my bots are running, but I can't control them. I entered my nickname as in the instructions. Injected CRNL but doesn't work. could you tell me what i did wrong

**Comment by depthso** [comment]
Did you put your display name or username?

**Comment by op-lum1x** [comment]
![image](https://user-images.githubusercontent.com/123903057/215521751-d81bb1d1-c3a1-4b00-9849-e13cf3344b11.png)

**Comment by op-lum1x** [comment]
![image](https://user-images.githubusercontent.com/123903057/215521981-31f2efb0-f6c6-4be1-8075-036d5c632dae.png)

**Comment by op-lum1x** [comment]
I added a display nickname to the config, but still the bots do not execute commands

**Comment by depthso** [comment]
Hmmm, interesting... Could you add a print function to the `ChatEvent` subroutine and see if it is fired? You can see the console output by pressing F9.

**Comment by op-lum1x** [comment]
I do not know how to do it. I don't know what an IDE is :(
