### ISSUE TITLE
Bots don't listen to any commands sent in chat

### ISSUE THREAD

**Issue by dothenotive** [depthso/Roblox-Botter#4]
Hi!

The issue title is self-explanatory, and, well, in my opinion, I don't think that it's your program's fault - more of a synapse x one.
Bots _do_ join the game, although they are not paying attention to any commands. I think it's because Synapse X isn't attached to bots' clients, since the aforementioned Syn X does not auto attach to these clients.

![image](https://user-images.githubusercontent.com/69473285/221361933-6c79301c-29e3-4aa7-888a-bc509dab72fc.png)

I noticed a print function(`print("Bot Controler loaded!")`) in the end of the BotController script, and it doesn't fire at all: 
![image](https://user-images.githubusercontent.com/69473285/221362009-192f251f-a16b-4120-80ea-9b12987dcd08.png)

I've looked at issues before, and I've seen that you told another guy to [sic] add a print function to the ChatEvent subroutine and see if it is fired. I did so, and here's the result: it only fires on the bot's client.
![image](https://user-images.githubusercontent.com/69473285/221362656-8b2a0696-6b4c-42f9-a0e9-9f0ba8084a4f.png)
![image](https://user-images.githubusercontent.com/69473285/221362220-2efbf35a-2d3f-477f-8418-0c9c3750be3d.png)
![image](https://user-images.githubusercontent.com/69473285/221362240-78d07d12-d3ac-4d8b-a2d9-1c4afba89111.png)

If you're wondering, I am using VScode!
I can tell you more if you can add me on discord: 2-1#8263

**Comment by dothenotive** [comment]
Edit: just checked the bot's client response, and here's what i got:
![image](https://user-images.githubusercontent.com/69473285/221362572-1e7dd12a-6aa3-4cf6-8d16-b240b514b2ad.png)

**Comment by dothenotive** [comment]
Nope, looks like you have to attach syn x to the bot's client.
![image](https://user-images.githubusercontent.com/69473285/221362954-8d374789-cfca-45f1-8ec2-11ad7a1f75c1.png)

After attaching:
![image](https://user-images.githubusercontent.com/69473285/221363025-aca77c21-05e9-44ae-928e-9233a7dd5895.png)

**Comment by depthso** [comment]
Hmmm, open up remote spy and make sure it logs requests from the client because this is new.

**Comment by Benneyz** [comment]
did you happen to find a solution? im also finding the same problem. im newer to all of this, so i'm not sure if its my fault or something in the code

**Comment by dothenotive** [comment]
> Hmmm, open up remote spy and make sure it logs requests from the client because this is new.
> 
> `loadstring(game:HttpGet("https://github.com/exxtremestuffs/SimpleSpySource/raw/master/SimpleSpy.lua"))()`

I think it's pointless doing that, because, well, the event is already getting fired(shown in screenshots above), although i'll try

**Comment by dothenotive** [comment]
It definitely works; 
![image](https://user-images.githubusercontent.com/69473285/221414177-db2dd6b9-216b-444e-b80e-49257459ef73.png)
although the bot doesn't say the message. I'm working on a quick fix, and, if it's gonna work, i'll make a pull request.

**Comment by dothenotive** [comment]
Now the bot listen to all commands; working on the hot-fix
![image](https://user-images.githubusercontent.com/69473285/221414325-7a3012d8-63d3-41a9-9134-8386162dbcc0.png)

**Comment by dothenotive** [comment]
reply to the comment above 
temp fix: https://github.com/depthso/Roblox-Botter/pull/5/commits/426f40dff6ed329b3a8bb99945f5cdf01bbe1730


Another issue - synapse X doesn't automatically attach to Roblox processes. I've tried setting the TimeBetween to 25, but syn x still doesn't attach to any processes.

**Comment by Benneyz** [comment]
sorry if im an idiot, but i just simply need to change the name to mine for it to work right? because I did that, and still i'm not seeing any success

**Comment by depthso** [comment]
> Another issue - synapse X doesn't automatically attach to Roblox processes. I've tried setting the TimeBetween to 25, but syn x still doesn't attach to any processes.

Yeah, I had this issue too which is why I've decided to create a second version that doesn't require Lua vm injection

**Comment by depthso** [comment]
> sorry if im an idiot, but i just simply need to change the name to mine for it to work right? because I did that, and still i'm not seeing any success
> 
> @dothenotive

Replace `Quandaledingle_Owl` with your username and not display name.
