### ISSUE TITLE
Header problems

### ISSUE THREAD

**Issue by Yaznae** [depthso/Roblox-Botter#9]
```PY
    req = requests.post(
        "https://auth.roblox.com/v1/authentication-ticket",
        headers={"Cookie": ".ROBLOSECURITY=" + Cookie}
    )

    csrf = req.headers['x-csrf-token']
```

This specific code does not work, haven't got my x-csrf-token.
I modified the code and successfully managed to get my token.
Here's the new code:
```PY
    req = requests.post(
        "http://auth.roblox.com/v1/usernames/validate",
        headers={
            "Accept": "applications/json",
            "Cookie": ".ROBLOSECURITY=" + Cookie
        }
    )

    csrf = req.headers['x-csrf-token']
```
    
New problem arises where I can't get my rbx-authentication-ticket, brings back 403 Status Code.
Any fixes?

**Comment by depthso** [comment]
Sorry for the very late reply, can I have more information about your environment such as: your operating system, IDE, python version etc

**Comment by Yaznae** [comment]
No worries.

Operating System: Windows 11 Home, Version 22H2, Build 22621.1413
IDE: Microsoft Visual Studio Code
Python Version: 3.9.1

**Comment by depthso** [comment]
Try usin

**Comment by depthso** [comment]
Interesting, have you tried manually Setting the token instead of fetching it first thing?


Ps, I accidentally closed the issue on mobile LOL.

**Comment by Gluck212** [comment]
I'm getting KeyError: 'rbx-authentication-ticket' error
